### ISSUE TITLE
Deleted branches

### ISSUE THREAD

**Issue by ZachOhara** [Thunderbots-5604/2014-Code#2]
@pranavmathur, @danielgrimshaw, @zachw000 

All the named branches and the working branch have been merged and deleted. It is recommended that you remove and re-clone the repository before continuing work, so it's easier to identify which branches still exist. Currently there are only unstable, Daniel's branch, and master, with unstable being the default.

Daniel, please merge and delete your branch as soon as gyro code is to a working state.

**Comment by danielgrimshaw** [comment]
Your merge broke all of the code, @ZachOhara 
Fix it.

**Comment by ZachOhara** [comment]
As soon as everyone has confirmed that they are aware of these changes, this issue will be closed.

**Comment by danielgrimshaw** [comment]
I think that everyone is aware of the changes. If not, they will find out soon enough.
