### ISSUE TITLE
autofixWhitespace.py does not work on linux

### ISSUE THREAD

**Issue by danielgrimshaw** [Thunderbots-5604/2014-Code#3]
I think that it is a problem with the generator, but I can't work out any way to fix it. Please add support for this @ZachOhara 
Cause of bug is most likely that linux uses '/' to denote path, where windows (and only windows) uses '\'

**Comment by ZachOhara** [comment]
This can be fixed using the os module for python, I believe. The method os.path.join will work on all systems.

**Comment by danielgrimshaw** [comment]
There is no problem with that method, but on linux it is ignoring the excludes (as in it is trying to correct them). When I tried to run autofixWhitespace it tried to correct all of the Xander_Drivers files.

**Comment by ZachOhara** [comment]
Fixed! The common module now relies on os.path.join for all its path-joining needs.

Please reopen the issue if it does not work, but at least all Windows functionality has been retained.
