### ISSUE TITLE
Whitespace script errors

### ISSUE THREAD

**Issue by ZachOhara** [Thunderbots-5604/2014-Code#4]
I've created a new branch called whitespace-fixing, and ran your script in that. You can view the commit for a full list of changes, but here are some things as I notice them. Examples are given for some items, although they may still appear in other places.

* "#else" preprocessor commands leave an indent on the following line (api.c:11)
* "#endif" preprocessor commands leave an indent on the following line (api/legacy/debug.c:14)
* Blank lines are all given no indent. Not something necessarily wrong, but something I stylistically disagree with, especially while in the context of a task or function.
* Names of loops in comments are creating indents on the following lines, where there should be no indent. This effect is compounded for multiline comments in which each line contains a loop name. (encoders.c:26)
* If a comment contains a loop name, and the following line is a function header or a bracketed loop, the entire function/loop will be given an extra indent. (math.c:28-36)
* Sometimes single-line loops are not being indented when they should be. I think this only happens with "for" (math.c:14)
* If a loop is bracketed, but the bracket is on the next line, the bracket will be given a bad indent, and the body of the block will be given a double indent. This isn't really something that we should be worried about because it's a style that we don't use. (auto/old/simple_auto.c:38-46)
* If a two-dimensional array is declared and initialized across multiple lines, no lines will be given the indent they deserve. (auto/ramp_goal_park_v3.c:44-54)
* A strange exception to item 4 on this list occurs in testing/sensorTesting.c and I'm not sure what's causing it (lines 12-16)

**Comment by danielgrimshaw** [comment]
The else and endif problems are easy to fix, blank lines need no indent, all that does is take up extra space on the computer, I'll take a look into points 4 and 5, they seem to be the same problem. I will ignore problem 7, it will require fully rewriting the code to fix.

**Comment by danielgrimshaw** [comment]
The preprocessor indentation problems have been fixed; the third point is not a problem; all problems with comments have been resolved.

**Comment by danielgrimshaw** [comment]
I might actually fix problem 7 if I get time.
