### ISSUE TITLE
initializeAPI causing robot to not start with debug line

### ISSUE THREAD

**Issue by pranavmathur** [Thunderbots-5604/2014-Code#7]
It causes the nxt to display WaitForStart forever when running from the debug window. Have not tested with competition controls.

@ZachOhara 
@danielgrimshaw 
@zachw000

**Comment by ZachOhara** [comment]
Is it possible that the debug window does not send a start signal?

**Comment by danielgrimshaw** [comment]
I think it is a feature of the Xander-Drivers, if it reads that something is not set up correctly, but the driver has been included for it, it automatically kills the code. I will comment out all of them.

**Comment by ZachOhara** [comment]
Guessing this has been fixed? Closing the issue.

**Comment by danielgrimshaw** [comment]
That was a theory, the code has been temporarily fixed, but not fully yet.
