### ISSUE TITLE
Gyro drivers- what to do?

### ISSUE THREAD

**Issue by ZachOhara** [Thunderbots-5604/2014-Code#8]
@danielgrimshaw , if you are finished with them, please merge and delete the branch into unstable. I made a commit that added the gyro sensor code from the 2015 repo, so at least make sure that it's correct.

**Comment by danielgrimshaw** [comment]
So you added the code that I committed earlier into 2015 to the 2014
code? You might want to revert that, said commit made several other
changes too. I think we can officially call the 2014 code finished,
unless someone really wants to complete it for the slim probability of
us being called as alternates. Also, I don't really like the API repo,
can't we just work on it from 2015 code? @pranavmathur @zachw000
@ZachOhara please use this issue to vote on deleting that repo.

**Comment by ZachOhara** [comment]
Clarification: Don't vote in this issue! Use the other one! It's in the 2015-code repo

I agree that 2014 is over, but I'd still like to leave it off in a good place. We should consolidate all of our branches to only one, make sure it compiles, and then release major version 1.0.0 as a final goodbye.
