### ISSUE TITLE
Petition to delete branch "Zach_W"

### ISSUE THREAD

**Issue by ZachOhara** [Thunderbots-5604/2014-Code#9]
It is currently 138 commits behind the default. Please respond by either saying yes or no. If no one objects, it will be deleted.

Please vote: @pranavmathur @danielgrimshaw @zachw000

**Comment by danielgrimshaw** [comment]
You have my complete permission to annihilate that branch, but only that branch.

**Comment by ZachOhara** [comment]
Please vote @pranavmathur and @zachw000

**Comment by ZachOhara** [comment]
Failure to vote has been assumed. Branch has been deleted.
